package kirc;

import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public final class KIRCFrame extends javax.swing.JFrame
{
    private final KIRC kirc;
    
    /**
     * Creates new form KIRCFrame
     */
    public KIRCFrame()
    {
        initComponents();
        
        kirc = new KIRC(this, "irc.freenode.org", "##kirctest", "k-test");
        
        userNameLabel.setText(kirc.getNick() + " λ");

        kirc.runClient();
    }
    
    public KIRCFrame getKIRCFrame()
    {
        return this;
    }
    
    public void addTab(final String s)
    {
        JPanel panel = (JPanel)makeChannelPanel();
        channelPane.addTab(s, panel);
        channelPane.setTabComponentAt(channelPane.indexOfComponent(panel),
                ChannelPane.getTitlePanel(channelPane, panel, s, kirc));
    }
    
    public void displayMessage(final String messageToDisplay, final int channelIndex)
    {
        SwingUtilities.invokeLater(() ->
        {
            ChannelPane channelArea = null;
            if(channelIndex < channelPane.getTabCount() && channelIndex > -1)
                channelArea = (ChannelPane)channelPane.getComponentAt(channelIndex);

            if(channelArea != null)
                channelArea.getTextArea().append(messageToDisplay);
        });
    }
    
    public void setTextFieldEditable(final boolean editable)
    {
        SwingUtilities.invokeLater(() ->
        {
            enterField.setEditable(editable);
        });
    }
    
    protected JComponent makeChannelPanel() 
    {
        ChannelPane channelArea = new ChannelPane();
        return channelArea;
    }
    
    public void setFocusOnChannel(final int i)
    {
        if(i < channelPane.getTabCount())
            channelPane.setSelectedIndex(i);
    }
    
    public int getChannelFocus()
    {
        return channelPane.getSelectedIndex();
    }
    
    public int getChannelPaneSize()
    {
        return channelPane.getTabCount();
    }
    
    public void setUserList(String[] users)
    {
        userList.setListData(users);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList();
        channelPane = new javax.swing.JTabbedPane();
        enterField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(userList);

        channelPane.setBackground(new java.awt.Color(204, 204, 204));
        channelPane.setBorder(null);
        channelPane.setMaximumSize(new java.awt.Dimension(100, 100));
        channelPane.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                channelPaneStateChanged(evt);
            }
        });

        enterField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                enterFieldActionPerformed(evt);
            }
        });

        userNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userNameLabel.setText("username");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Users");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Channel banner here");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                            .addComponent(channelPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(channelPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_enterFieldActionPerformed
    {//GEN-HEADEREND:event_enterFieldActionPerformed
        kirc.enterFieldFired(enterField.getText());
        enterField.setText("");
    }//GEN-LAST:event_enterFieldActionPerformed

    private void channelPaneStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_channelPaneStateChanged
    {//GEN-HEADEREND:event_channelPaneStateChanged
        int channelIndex = channelPane.getSelectedIndex();
        Channel ch = kirc.getChannel(channelIndex);
        if(ch != null)
        {
            ArrayList<String> userList = ch.getUsersList();
            setUserList(userList.toArray(new String[userList.size()]));
        }
    }//GEN-LAST:event_channelPaneStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        KIRCFrame frame = new KIRCFrame();
        KIRC kirc = new KIRC(frame, "irc.freenode.org", "##kirctest", "k-test");
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(KIRCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(KIRCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(KIRCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(KIRCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                javax.swing.JFrame frame = new javax.swing.JFrame("kIRC");
                frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                frame.getContentPane().add(new KIRCFrame());
                frame.pack();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane channelPane;
    private javax.swing.JTextField enterField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList userList;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
